[page.default]
file = "../../../../_default.page.toml"

[page.template]
path = '../../../../_default.page.html'

[page.builder]
page = "create.page.js"
path = "/0/admin/blog/posts/create"

[page.builder.headers]
Access-Control-Allow-Origin = '*'
Access-Control-Allow-Methods = 'GET'
Content-Security-Policy = 'frame-ancestors'

[page.definition]
title = 'Post Edit | Fustak'
canonical = 'https://###URL###/0/admin/blog/posts/create'
styles = [
    '../../../../styles/normalize.css',
    '../../../../styles/reset.css',
    '../../../../styles/styles.css',
    '../../../../components/switch.css',
    './create.style.css',
    '../../../../../../node_modules/@mdxeditor/editor/dist/style.css',
]

[[page.definition.stylesheets]]
href = 'asset(/styles/prose.css)'

[[page.definition.scripts]]
src = 'dist(/pages/create.posts.island.js)'
async = true
